# After changing this file, check it on:
#   http://lint.travis-ci.org/

language: python
python:
  - "3.4.3"
# command to install dependencies
before_install:
  - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ trusty main universe"
  - sudo apt-get update
  - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ vivid main universe"
  - sudo apt-get update
  # - sudo apt-get install -qq python-numpy python-six
  - sudo apt-get --ignore-missing install build-essential python-dev python3-dev libquantlib0-dev libncursesw5-dev libssl-dev libgdbm-dev libc6-dev libsqlite3-dev tk-dev libbz2-dev
  - pip install -r requirements.txt
install:
  - python -m spacy.en.download
cache:
  directories:
    - /home/travis/virtualenv/python3.4.3/lib/python3.4/site-packages
    - /home/travis/virtualenv/python3.4.3/lib/python3.4/site-packages/spacy/en/data/
# command to run tests
script:
  - python -m unittest discover -s test -p 'test*.py'
